# DEVICE PATH
DEVICE_PATH := device/tecno/KG5n

# BUILDING SUPPORT
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# ARCHITECTURE
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a75

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_CPU_SMP := true
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true

# 64-bit
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_IS_64_BIT := true

# BOOTLOADER
TARGET_NO_RADIOIMAGE := true
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := KG5n
TARGET_USES_UEFI := true

# KERNEL & BOOTIMG (offsets from original tree)
BOARD_KERNEL_CMDLINE := audit=0 console=ttyS1,115200n8 earlycon=uart8250,mmio32,0x7010000000000000000000000
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x05400000
BOARD_KERNEL_SECOND_OFFSET := 0x00000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_DTB_OFFSET := 0x01f00000
BOARD_BOOTIMG_HEADER_VERSION := 2

BOARD_MKBOOTIMG_ARGS := --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --dtb $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)

# PARTITION SIZES
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_HAS_NO_REAL_SDCARD := true

# DYNAMIC PARTITIONS
BOARD_SUPER_PARTITION_GROUPS := tecno_dynamic_partitions
BOARD_TECNO_DYNAMIC_PARTITIONS_SIZE := 9122611200
BOARD_TECNO_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext vendor product

# RECOVERY AS BOOT (V-A/B)
BOARD_USES_RECOVERY_AS_BOOT := true
TARGET_NO_RECOVERY := true
TW_HAS_NO_RECOVERY_PARTITION := true
BOARD_USES_METADATA_PARTITION := true

# ==========================================
# DISPLAY & GRAPHICS (FIX FOR ATOMIC COMMIT -22)
# ==========================================
TW_THEME := portrait_hdpi
TARGET_SCREEN_DENSITY := 320
TW_FRAMERATE := 90

# Ошибка -22 часто лечится правильным форматом пикселей.
# В оригинале RGBX_8888, пробуем его, но с поддержкой DRM
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# Явно включаем DRM и выключаем кривой FB
TW_USE_MINUI_WITH_DRM := true
TW_USE_MINUI_WITH_FB := false

# Рендерер для OrangeFox UI
TW_USE_OPENGL_RENDERER := true
TW_INCLUDE_LIBGGL := true
TW_NO_RECOVERY_BLUR := true

# Путь яркости из твоего лога (recovery.log)
TW_BRIGHTNESS_PATH := "/sys/devices/platform/soc/soc:ap-ahb/31100000.dsi/31100000.dsi.0/display/panel0/sprd_backlight/brightness"
TW_MAX_BRIGHTNESS := 4095
TW_DEFAULT_BRIGHTNESS := 1200

# Чтобы не гас экран в процессе
TW_NO_SCREEN_BLANK := true
TW_SCREEN_BLANK_ON_BOOT := false

# ==========================================
# ORANGEFOX FLAGS (OFOX)
# ==========================================
FOX_VERSION := R11.3
FOX_BUILD_TYPE := Stable
FOX_RECOVERY_INSTALL_PARTITION := "/boot"
FOX_RECOVERY_SYSTEM_PARTITION := "/system"
FOX_VIRTUAL_AB_DEVICE := true
AB_OTA_UPDATER := true

# Опции системы и инструментов
FOX_REPLACE_TOOLBOX_GETPROP := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_SED_BINARY := 1
FOX_USE_XZ_UTILS := 1
FOX_ASH_IS_BASH := 1
FOX_ENABLE_APP_MANAGER := 1

# Безопасность и исключения
TW_EXCLUDE_APEX := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_INCLUDE_CRYPTO := true
TW_USE_TOOLBOX := true
TW_NO_LEGACY_PROPS := true

# ==========================================
# MTP & USB
# ==========================================
TW_HAS_MTP := true
TW_MTP_DEVICE := /dev/mtp_usb
TARGET_USE_CUSTOM_LUN_FILE_PATH := /config/usb_gadget/g1/functions/mass_storage/lun.%d/file

# FSTAB
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab
